### ISSUE TITLE
Use babel-plugin-add-module-exports to export the plugin without defaults

### ISSUE THREAD

**Issue by germanattanasio** [forestryio/markdown-it-kramdown-attrs#1]
Because you are using babel, the compiled javascript exports a `default` variable.

Steps to reproduce:

```
npm install markdown-it-kramdown-attrs
node -e "console.log(require('markdown-it-kramdown-attrs'))"
```

Output:

```
{ default: [Function: i] }
```

Desired output:

```
{ Function: i }
```

The only way to use this module in `markdown-it` is if we add `.default`:

``` js
const markdown = require('markdown-it-kramdown-attrs');
const kramdownAttrs = require('markdown-it-kramdown-attrs');

const renderer = new MarkdownIt();
renderer.use(kramdownAttrs.default);
```

You need to add `babel-plugin-add-module-exports` to your plugins so that people that aren't using babel can still use this wonderful plugin.

More info: http://stackoverflow.com/questions/33505992/babel-6-changes-how-it-exports-default

**Comment by envygeeks** [comment]
I didn't even know about that plugin, thanks so much for this because it always got to me on another project I had to do `require("module").default` :laughing:.
